name: Metrics
on:
  # Schedule updates (00:30 && 12:30 UTC daily)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: thomasdavis
          template: classic
          config_gemoji: yes # use additional non-unicode emoji
          config_timezone: America/Sao_Paulo
          retries: 3
          retries_delay: 300
          # repositories_batch: 5
          use_prebuilt_image: yes # faster execution

          # base
          base: header, activity, community, repositories, metadata
          repositories_forks: no
          repositories_affiliations: owner
          repositories_skipped: thomasdavis/thomasdavis

          plugin_discussions: yes

          # The languages plugin displays which programming languages you use the most across all your repositories.
          plugin_languages: yes
          # plugin_languages_skipped: my-test-repo                       # List of repositories to skip
          # plugin_languages_colors: "0:orange, javascript:#ff0000, ..." # Make most used languages orange and JavaScript red
          plugin_languages_details: bytes-size, percentage # Additionally display total bytes size and percentage
          # plugin_languages_threshold: 2%                               # Hides all languages less than 2%
          plugin_languages_sections: most-used, recently-used

          # The reactions plugin displays overall reactions on your recent issues and issue comments.
          plugin_reactions: yes
          plugin_reactions_limit: 200 # Compute reactions over last 200 issue comments
          plugin_reactions_days: 90 # Compute reactions on issue comments posted less than 90 days ago
          plugin_reactions_details: count # Display reactions count but not percentage

          # The followup plugin displays the ratio of open/closed issues and the ratio of open/merged pull requests across all your repositories, which shows if they're well-maintained or not.
          plugin_followup: yes
          plugin_followup_sections: repositories, user

          # The lines of code plugin displays the number of lines of code you have added and removed across all of your repositories.
          plugin_lines: yes

          # The repositories traffic plugin displays the number of page views across your repositories.
          plugin_traffic: yes

          plugin_notable: yes
          plugin_notable_filter: stars:>50 # Only display repositories with 500 stars or more (syntax based on GitHub search query)
          plugin_notable_from: organization # Only display contributions within organization repositories
          plugin_notable_repositories: yes # Display repositories name instead of only organization name
          plugin_notable_indepth: yes # Gather additional informations about contributions
